// ============================================================
// KTXGo – Local Product Catalog
// Vietnamese student store: Food, Drinks, Stationery
// MSSV: 23694851
// ============================================================

// Type defined here to avoid circular import with productApi.ts
export interface LocalProduct {
  id: number;
  title: string;
  priceVND: number;
  description: string;
  category: 'FOOD' | 'DRINK' | 'STATIONERY';
  categoryLabel: string;
  image: string;
  rating: { rate: number; count: number };
}

// Images from Picsum with consistent seeds per product
// Food: warm tones, Drink: cool tones, Stationery: neutral tones

export const LOCAL_PRODUCTS: LocalProduct[] = [
  // ──────────────────────────────────────────────────────────
  // FOOD – Đồ ăn (10 products, IDs 1–10)
  // ──────────────────────────────────────────────────────────
  {
    id: 1,
    title: 'Mì Hảo Hảo Tôm Chua Cay',
    priceVND: 5000,
    description: 'Mì ăn liền vị tôm chua cay Hảo Hảo, phù hợp cho sinh viên ăn nhanh, tiện lợi và no lâu.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/mi-hao-hao/400/400',
    rating: { rate: 4.5, count: 320 },
  },
  {
    id: 2,
    title: 'Mì Omachi Bò Hầm',
    priceVND: 7000,
    description: 'Mì khoai tây Omachi vị bò hầm thơm ngon, không nhão, phù hợp cho sinh viên bận rộn.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/mi-omachi/400/400',
    rating: { rate: 4.6, count: 285 },
  },
  {
    id: 3,
    title: 'Bánh Mì Sandwich',
    priceVND: 15000,
    description: 'Bánh mì sandwich nhân trứng và rau, ăn sáng tiện lợi cho sinh viên.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/banh-mi/400/400',
    rating: { rate: 4.3, count: 198 },
  },
  {
    id: 4,
    title: 'Xúc Xích Heo Vissan',
    priceVND: 8000,
    description: 'Xúc xích heo Vissan đóng gói, dễ ăn, có thể ăn liền hoặc chiên nhanh.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/xuc-xich/400/400',
    rating: { rate: 4.2, count: 156 },
  },
  {
    id: 5,
    title: 'Bánh Bao Nhân Thịt',
    priceVND: 10000,
    description: 'Bánh bao hấp nhân thịt heo, ăn nóng ngon miệng, no lâu.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/banh-bao/400/400',
    rating: { rate: 4.4, count: 210 },
  },
  {
    id: 6,
    title: 'Snack Poca Vị Bò',
    priceVND: 6000,
    description: 'Snack khoai tây Poca vị bò nướng BBQ giòn tan, lý tưởng để vừa học vừa ăn vặt.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/snack-poca/400/400',
    rating: { rate: 4.1, count: 301 },
  },
  {
    id: 7,
    title: 'Bánh Quy Oreo',
    priceVND: 12000,
    description: 'Bánh quy Oreo vị socola và kem vanilla, thích hợp ăn kèm sữa hoặc ăn vặt.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/banh-quy-oreo/400/400',
    rating: { rate: 4.7, count: 412 },
  },
  {
    id: 8,
    title: 'Cơm Hộp Gà Chiên',
    priceVND: 35000,
    description: 'Cơm hộp gà chiên giòn, có rau xào và canh, đủ dinh dưỡng cho bữa trưa sinh viên.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/com-hop-ga/400/400',
    rating: { rate: 4.5, count: 175 },
  },
  {
    id: 9,
    title: 'Cá Viên Chiên',
    priceVND: 5000,
    description: 'Cá viên chiên giòn ăn kèm tương ớt, món ăn vặt bình dân quen thuộc của sinh viên.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/ca-vien/400/400',
    rating: { rate: 4.0, count: 223 },
  },
  {
    id: 10,
    title: 'Bánh Tráng Nướng Phô Mai',
    priceVND: 8000,
    description: 'Bánh tráng nướng phủ phô mai, trứng, hành lá — đặc sản ăn vặt Đà Lạt nổi tiếng.',
    category: 'FOOD',
    categoryLabel: 'Đồ ăn',
    image: 'https://picsum.photos/seed/banh-trang-nuong/400/400',
    rating: { rate: 4.6, count: 267 },
  },

  // ──────────────────────────────────────────────────────────
  // DRINK – Nước uống (10 products, IDs 11–20)
  // ──────────────────────────────────────────────────────────
  {
    id: 11,
    title: 'Nước Suối Aquafina 500ml',
    priceVND: 7000,
    description: 'Nước uống tinh khiết Aquafina 500ml, tiện lợi cho học tập và sinh hoạt hằng ngày.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/nuoc-aquafina/400/400',
    rating: { rate: 4.3, count: 540 },
  },
  {
    id: 12,
    title: 'Coca Cola Lon 330ml',
    priceVND: 10000,
    description: 'Nước ngọt Coca Cola có ga lon 330ml, giải khát tức thì sau giờ học.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/coca-cola/400/400',
    rating: { rate: 4.5, count: 620 },
  },
  {
    id: 13,
    title: 'Pepsi Lon 330ml',
    priceVND: 10000,
    description: 'Nước ngọt Pepsi có ga lon 330ml, vị ngọt đặc trưng, giải khát mát lạnh.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/pepsi-lon/400/400',
    rating: { rate: 4.4, count: 480 },
  },
  {
    id: 14,
    title: 'Sting Dâu Lon 330ml',
    priceVND: 10000,
    description: 'Nước tăng lực Sting vị dâu lon 330ml, bổ sung năng lượng khi học và thi.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/sting-lon/400/400',
    rating: { rate: 4.2, count: 355 },
  },
  {
    id: 15,
    title: 'Trà Xanh Không Độ 500ml',
    priceVND: 10000,
    description: 'Trà xanh Không Độ chai 500ml, thanh mát, ít ngọt, tốt cho sức khoẻ.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/tra-xanh/400/400',
    rating: { rate: 4.4, count: 398 },
  },
  {
    id: 16,
    title: 'Nước Cam Minute Maid 450ml',
    priceVND: 12000,
    description: 'Nước cam ép Minute Maid 450ml, giàu vitamin C, thơm ngon tự nhiên.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/nuoc-cam/400/400',
    rating: { rate: 4.3, count: 290 },
  },
  {
    id: 17,
    title: 'Sữa Tươi Vinamilk 180ml',
    priceVND: 8000,
    description: 'Sữa tươi tiệt trùng Vinamilk 180ml, bổ sung canxi và dinh dưỡng cho sinh viên.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/sua-vinamilk/400/400',
    rating: { rate: 4.6, count: 512 },
  },
  {
    id: 18,
    title: 'Nước Tăng Lực Redbull 250ml',
    priceVND: 12000,
    description: 'Nước tăng lực Red Bull lon 250ml, tăng sự tập trung và tỉnh táo khi ôn thi.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/redbull/400/400',
    rating: { rate: 4.4, count: 433 },
  },
  {
    id: 19,
    title: 'Trà Đào Cam Sả 500ml',
    priceVND: 15000,
    description: 'Trà đào cam sả đóng chai 500ml, hương vị thơm mát, giải nhiệt cực tốt.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/tra-dao/400/400',
    rating: { rate: 4.5, count: 367 },
  },
  {
    id: 20,
    title: 'Sữa Đậu Nành Fami 200ml',
    priceVND: 6000,
    description: 'Sữa đậu nành Fami 200ml, thanh đạm thực vật, tốt cho sức khoẻ và học tập.',
    category: 'DRINK',
    categoryLabel: 'Nước uống',
    image: 'https://picsum.photos/seed/sua-dau-nanh/400/400',
    rating: { rate: 4.2, count: 278 },
  },

  // ──────────────────────────────────────────────────────────
  // STATIONERY – Văn phòng phẩm (10 products, IDs 21–30)
  // ──────────────────────────────────────────────────────────
  {
    id: 21,
    title: 'Bút Bi Thiên Long 0.5mm',
    priceVND: 4000,
    description: 'Bút bi mực xanh Thiên Long ngòi 0.5mm, viết trơn, không nhòe, phù hợp ghi chép hằng ngày.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/but-bi/400/400',
    rating: { rate: 4.5, count: 680 },
  },
  {
    id: 22,
    title: 'Bút Chì 2B Staedtler',
    priceVND: 5000,
    description: 'Bút chì 2B Staedtler, nét đậm, phù hợp vẽ kỹ thuật, tô trắc nghiệm và phác thảo.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/but-chi/400/400',
    rating: { rate: 4.4, count: 390 },
  },
  {
    id: 23,
    title: 'Tập Vở 200 Trang Hồng Hà',
    priceVND: 18000,
    description: 'Vở kẻ ngang 200 trang Hồng Hà, giấy trắng dày, bìa cứng chắc chắn.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/tap-vo/400/400',
    rating: { rate: 4.6, count: 445 },
  },
  {
    id: 24,
    title: 'Giấy In A4 Double A (100 tờ)',
    priceVND: 30000,
    description: 'Giấy in A4 Double A 80gsm, 100 tờ/tập, phù hợp in tài liệu học tập và báo cáo.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/giay-a4/400/400',
    rating: { rate: 4.5, count: 312 },
  },
  {
    id: 25,
    title: 'Thước Kẻ 30cm',
    priceVND: 8000,
    description: 'Thước kẻ nhựa trong 30cm, có vạch mm rõ ràng, dùng cho vẽ và đo đạc.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/thuoc-ke/400/400',
    rating: { rate: 4.3, count: 256 },
  },
  {
    id: 26,
    title: 'Gôm Tẩy Staedtler Mars',
    priceVND: 6000,
    description: 'Gôm tẩy Staedtler Mars màu trắng, tẩy sạch không nhòe, không làm rách giấy.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/gom-tay/400/400',
    rating: { rate: 4.4, count: 187 },
  },
  {
    id: 27,
    title: 'Bút Highlight 4 Màu',
    priceVND: 25000,
    description: 'Bộ 4 bút dạ quang Thiên Long màu vàng, xanh, hồng, cam — đánh dấu tài liệu học.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/but-highlight/400/400',
    rating: { rate: 4.6, count: 340 },
  },
  {
    id: 28,
    title: 'Bút Lông Bảng Whiteboard',
    priceVND: 12000,
    description: 'Bút lông viết bảng trắng màu đen, mực xoá được, phù hợp học nhóm và thuyết trình.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/but-long/400/400',
    rating: { rate: 4.2, count: 215 },
  },
  {
    id: 29,
    title: 'Sổ Tay A5 Bìa Cứng',
    priceVND: 35000,
    description: 'Sổ tay A5 bìa cứng 200 trang, ghi chú, lên kế hoạch, hoặc nhật ký học tập.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/so-tay/400/400',
    rating: { rate: 4.7, count: 298 },
  },
  {
    id: 30,
    title: 'Keo Dán UHU 21g',
    priceVND: 15000,
    description: 'Keo dán UHU 21g dạng stick, dán giấy, bìa, không nhòe — tiện dùng làm đồ án.',
    category: 'STATIONERY',
    categoryLabel: 'Văn phòng phẩm',
    image: 'https://picsum.photos/seed/keo-dan/400/400',
    rating: { rate: 4.3, count: 172 },
  },
];
